config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :questions, except: [:show]

  resources :questions, only: [:show] do
    resources :answers, only: [:index, :create]
  end


end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :description, length: {minimum: 50}, presence: true
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, length: {minimum: 20}, presence: true
  validates :description, length: {minimum: 50}, presence: true
  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question

    if @answer.save
      flash[:notice] = "Answer saved successfully."
      redirect_to question_path(@question)
    else
      flash[:alert] = "Failed to save answer"
      if @question.answers.length > 0
        @answers = @question.answers
      end
      render "questions/show"
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(id: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    if @question.answers.length > 0
      @answers = @question.answers
    else
      @answers = nil
    end
  end


  def new
    @question = Question.new
  end

  def create
  @question = Question.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end

end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">RescueMission</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
    <br />
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Destroy', @question, method: :delete, data: {confirm: 'Are you sure?'} %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Questions</h1>


<ul>
  <% @questions.each do |question| %>
    <li>
      <%= link_to question.title, question_path(question)  %>
    </li>
  <% end %>
</ul>

<%= link_to 'Submit a question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<h3>
  <strong>Title:</strong>
  <%= @question.title %>
</h3>
<br />

<h4>
  <strong>Description:</strong>
  <br />
  <%= @question.description %>
</h4>
<br />
<br />
<h4>New Answer</h4>

<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Destroy', @question, method: :delete, data: {confirm: 'Are you sure?'} %> |
<%= link_to 'Back', questions_path %>

<p>
  <% if @answers %>
   <strong>Answers:</strong>
    <ul>
    <% @answers.each do |answer| %>
      <li><%= answer.description %><br /></li>
    <% end %>
    </ul>
  <% end %>
</p>